"""add login_tokens table

Revision ID: 1603f8fb4475
Revises: 9724232fac2d
Create Date: 2026-05-28 12:53:00.841149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1603f8fb4475'
down_revision = '9724232fac2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('next_url', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_tokens_token'))

    op.drop_table('login_tokens')
    # ### end Alembic commands ###
