"""add_email_verified_and_notifications

Revision ID: 2596338ae9ea
Revises: 5071b7099930
Create Date: 2026-05-28 14:35:40.924222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2596338ae9ea'
down_revision = '5071b7099930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add as nullable first, backfill, then add NOT NULL constraint
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.execute("UPDATE users SET email_verified = true WHERE email_verified IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified', nullable=False)
    # Backfill uid to FS-XXXXXX format before shrinking the column. Keep the
    # Postgres expression for production, but use SQLite-compatible SQL so a
    # fresh local dev database can run the full migration chain.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            UPDATE users
            SET uid = 'FS-' || LPAD((FLOOR(RANDOM() * 1000000))::INT::TEXT, 6, '0')
            WHERE LENGTH(uid) > 12
        """)
    else:
        op.execute("""
            UPDATE users
            SET uid = 'FS-' || SUBSTR('000000' || ABS(RANDOM() % 1000000), -6, 6)
            WHERE LENGTH(uid) > 12
        """)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
