"""social state: thread_reads, thread_votes, activity_events, last_active_at, hot_score

Revision ID: 741e8374db51
Revises: 55d837af7f1c
Create Date: 2026-06-12 12:56:41.368591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741e8374db51'
down_revision = '55d837af7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_group_id'), ['group_id'], unique=False)

    op.create_table('thread_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['game_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'thread_id', name='uq_thread_read')
    )
    with op.batch_alter_table('thread_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_reads_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_reads_user_id'), ['user_id'], unique=False)

    op.create_table('thread_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['game_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_vote')
    )
    with op.batch_alter_table('thread_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_votes_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('game_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hot_score', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')

    with op.batch_alter_table('game_threads', schema=None) as batch_op:
        batch_op.drop_column('hot_score')

    with op.batch_alter_table('thread_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_thread_votes_thread_id'))

    op.drop_table('thread_votes')
    with op.batch_alter_table('thread_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_thread_reads_thread_id'))

    op.drop_table('thread_reads')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_group_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_created_at'))

    op.drop_table('activity_events')
    # ### end Alembic commands ###
