"""user_profile_fields_audit_log

Revision ID: e2d050fb28f0
Revises: a8d6d39f9502
Create Date: 2026-05-27 02:48:44.569115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d050fb28f0'
down_revision = 'a8d6d39f9502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add nullable first so existing rows don't violate NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('display_preference', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('has_completed_profile', sa.Boolean(), nullable=True))

    # Backfill existing rows
    import uuid
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id FROM users")).fetchall()
    for (user_id,) in users:
        conn.execute(
            sa.text("UPDATE users SET uid=:uid, display_preference='username', has_completed_profile=false WHERE id=:id"),
            {"uid": str(uuid.uuid4()), "id": user_id}
        )

    # Now enforce NOT NULL and add unique index
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uid', nullable=False)
        batch_op.alter_column('display_preference', nullable=False)
        batch_op.alter_column('has_completed_profile', nullable=False)
        batch_op.create_index(batch_op.f('ix_users_uid'), ['uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uid'))
        batch_op.drop_column('has_completed_profile')
        batch_op.drop_column('display_preference')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('uid')

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
